import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import styles from './page.module.scss'
import Image from 'next/image'
import Header from '../widgets/header/header'
import ReactQueryProvider from '@/app/providers/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <main className={styles.main}>
            <div className={styles.container}>
              <Header />
              {children}
            </div>
          </main>
          <footer className={styles.footer}>
            <div className={styles.container}>
              <a
                href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image aria-hidden src="/file.svg" alt="File icon" width={16} height={16} />
                Learn
              </a>
              <a
                href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image aria-hidden src="/window.svg" alt="Window icon" width={16} height={16} />
                Examples
              </a>
              <a
                href="https://nextjs.org?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image aria-hidden src="/globe.svg" alt="Globe icon" width={16} height={16} />
                Go to nextjs.org →
              </a>
            </div>
          </footer>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
